name: Build BONELAB Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore bonelab_template.sln

    - name: Build Solution
      run: msbuild bonelab_template.sln /p:Configuration=Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FusionStatsNametags
        path: '**/bin/Release/**/*.dll'
